Lyl/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include("orders.urls",namespace='orders')),
    
]

orders/urls.py
from django.conf.urls import include,url
from . import views
from orders.views import ResultView,LoginView,index



urlpatterns = [

   	url(r'^index$',views.index,name='index'),#首页
    url(r'^result_time(?P<pindex>\d*)$',ResultView.as_view(),name='result_time'),#多条件查询
    url(r'^',LoginView.as_view(),name='login'),
]

orders/models.py
from django.db import models


# Create your models here.

class Orders(models.Model):
    usertoken = models.CharField(max_length=40)
    orderno = models.CharField(unique=True, max_length=40)
    orderamount = models.DecimalField(max_digits=65535, decimal_places=65535)
    created_at = models.BigIntegerField(blank=True, null=True)
    is_filled = models.IntegerField(blank=True, null=True)
    service_type = models.IntegerField(blank=True, null=True)
    source_id=models.IntegerField(blank=True,null=True)

    """def get_dict(self):
    	d={
    		"usertoken":self.usertoken,
    		"orderno":self.orderno,
    		"orderamounter":self.orderamounter,
    		"created_at":self.created_at,
    		"is_filled":sel.is_filled,
    		"service_type":self.service_type,
    		"source_id":self.source_id
    	}
    	return d"""

    class Meta:
    	managed=False
    	db_table='orders'

orders/views.py
from django.shortcuts import render,redirect
from orders.models import Orders
from django.http import HttpResponse,HttpResponseRedirect
import time
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.db.models import Count
from django.core.paginator import Paginator
from django.views.generic import View,ListView
from django.contrib.auth.models import User,auth
from django.contrib.auth import authenticate,login
from utils.mini import LoginRequiredMini
import math
from django.views.generic import ListView
from django.views import generic
from utils import constants,get_page
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse
from django_redis import get_redis_connection
from django.conf import settings
from django.core.cache import cache



# Create your views here.
#查询某一段时间的订单	
class ResultView(LoginRequiredMini,View):
	def get(self,request,pindex):
		#从redis数据库中
		key_str=request.COOKIES.get('result_key')
		print(key_str)
		if not key_str:
			key_str='nokey'
		flage=cache.has_key(key_str)		
		if flage:	
			try:
				olist=cache.get(key_str)
			except Exception as e:
				return HttpResponse("数据查询失败")

		else:
			orderMethod=request.GET.get('orderMethod')
			start_time_stamp=request.GET.get("start_timestamp")
			end_time_stamp=request.GET.get("end_timestamp")
			usertoken=request.GET.get("usertoken")#	用户标识 选填
			orderno=request.GET.get("orderno")#订单号 选填
			orderType=request.GET.get("orderType")#订单种类 必填
			isfilled=request.GET.get("isfilled")#是否已分发 必填

			if orderMethod!='3':
				try:
					if not all([start_time_stamp,end_time_stamp]):
						return HttpResponse("开始时间与结束时间必填")
					start_timestamp=int(start_time_stamp)
					end_time_stamp=int(end_time_stamp)
					olist=Orders.objects.filter(created_at__gt=start_time_stamp,created_at__lt=end_time_stamp)
					if usertoken!='0':
						olist=olist.filter(usertoken='%s'%usertoken)
					if orderType=='2':
						olist=olist.filter(orderno__contains='LYL2')
					if orderType=='3':
						olist=olist.filter(orderno__contains='LYLGD')
					if orderno!='0':
						olist=olist.filter(orderno='%s'%orderno)
					if isfilled=='0':
						olist=olist.filter(is_filled=0)
					if isfilled=='1':
						olist=olist.filter(is_filled=1)
				except Exception as e:
					return HttpResponse("数据查询错误")

			else:
				try:
					olist=Orders.objects.filter(orderno='%s'%orderno)
				except Exception as e:
					return HttpResponse("数据查询错误")
		
			try:
				#将得到的结果存进redis数据库中
				cache.set(key_str,olist,60*60)
			except Exception as e:
				return HttpResponse("数据保存失败")
		#分页
		olength=len(olist)
		paginator=Paginator(olist,constants.HTML_PAGE_NUMS) #每页5条
		if pindex=="":
			pindex=1
		else:
			pindex=int(pindex)
		page=paginator.page(pindex)
		total_page_number=paginator.num_pages
		len_pindex=math.ceil(float(olength/constants.HTML_PAGE_NUMS))
		page_list=get_page.get_pages(int(total_page_number),int(pindex))
		if pindex>1:
			flage=True
		return render(request,'htmls/template.html',{'page':page,'page_list':page_list,'olength':olength,'len_pindex':len_pindex,'flage':flage})

#登录
class LoginView(View):
	def get(self,request):
		return render(request,'htmls/login.html')

	def post(self,request):
		username=request.POST.get('username')
		password=request.POST.get('password')
		user = auth.authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				auth.login(request,user)
				next_url=request.GET.get('next',reverse('orders:index'))
				response=redirect(next_url)
				return response
			else:
				return render(request,'htmls/login.html',{'errmsg':'该用户不存在'})
		else:
			return render(request,'htmls/login.html',{'errmsg':'用户名或密码错误'})

#跳转首页
def index(request):
	return render(request,'htmls/result.html')

orders/templates/htmls/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>联金数据库查询系统</title>
</head>
<body>
	<div >
		<div style="display: inline; bottom: 30px;" >
		<h1 style="display: inline; " >联金数据库查询系统 </h1>
	</div>
	<span><img src="{% static 'images/1528175965.png' %}" style="height: 73px;width: 255px;" id="im"></span>
	
	</div>
	
	<div>
	<hr>
	<h2>根据时间查询订单</h2>
	<h4 style="color:red " >默认时间为过去一小时</h4>
	<form action="/result_time" method='POST'>
		{% csrf_token %}

		请输入开始时间<input type="text" name="start_time" placeholder="XXXX/XX/XX XX:XX:XX" value="{{ startTime }}">
		请输入结束时间<input type="text" name="end_time"placeholder="XXXX/XX/XX XX:XX:XX" value="{{ endTime }}">
		<button id="bt" >查询</button>
		<h4 style="color: red">{{errormge1}}</h4>
	</form>
	<hr>
	<h2>根据用户标识查找该用户某一时间范围订单详情</h2>
	<h4 style="color:red " >默认时间为过去一小时</h4>
	<form action="/result_usertoken" method='POST'>
		{% csrf_token %}
		请输入用户标识<input type="text" name="ausertoken" >
		请输入开始时间<input type="text" name="start_time" placeholder="XXXX/XX/XX XX:XX:XX" value="{{ startTime }}" >
		请输入结束时间<input type="text" name="end_time"placeholder="XXXX/XX/XX XX:XX:XX" value="{{ endTime }}" >
		<button>查询</button>
		<h4 style="color: red">{{errormge2}}</h4>
	</form>
	<hr>
	<h2>根据订单号查询订单详细情况</h2>
	<form action="/result_orderno" method='POST'>
		{% csrf_token %}
		请输入订单号<input type="text" name="orderno" >
		<button>查询</button>
		<h4 style="color: red">{{errormge3}}</h4>
	</form>
	<hr>
	<h2>查询某段时间联金是否分发成功</h2>
	<h4 style="color:red " >默认时间为过去一小时</h4>
	<form action="/is_filled" method='POST'>
		{% csrf_token %}

		请输入开始时间<input type="text" name="start_time" placeholder="XXXX/XX/XX XX:XX:XX" value="{{ startTime }}">
		请输入结束时间<input type="text" name="end_time"placeholder="XXXX/XX/XX XX:XX:XX" value="{{ endTime }}">
		<button>查询</button>
		<h4 style="color: red">{{errormge4}}</h4>
		<a href="/newresult.html">aaaaa</a>
	</form>

	</div>
</body>
</html>

orders/templates/htmls/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>联金数据库查询系统</title>
<style type="text/css">
	#dv{
		margin:0 auto;
		padding-left: auto;
		width:427px;
		margin-top: 200px;


	}
	#im{
		height: 73px;
		width: 255px;
	}

</style>
</head>
<body>
	
	<DIV id="dv" >
	<img src="{% static 'images/1528175965.png' %}" id="im">
	<h1>联金数据库查询系统</h1>
	<form action="{% url 'orders:login' %}" method="post" >
		{% csrf_token %}
		用户名：<input type="text" name="username"><br>
		密码  &nbsp&nbsp&nbsp：<input type="password" name="password"><br>
		<button id="bt">登录</button><br>
		<span style="color: red;">{{errmsg}}</span>

	</form>
	</DIV>
	<!--
	<DIV id="dv" >
	<img src="{% static 'images/1528175965.png' %}" id="im">
	<form class="form-horizontal" action="{% url 'orders:login' %}" method="post">
		{% csrf_token %}
			<div class="form-group">
			  
			  <div class="col-sm-10">
			    用户名：<input type="text" name="username" class="form-control" id="username" placeholder="请输入用户名">
			  </div>
			</div>
			<div class="form-group">
			 
			  <div class="col-sm-10">
			    密码&nbsp&nbsp&nbsp：<input type="password" name="password" class="form-control" id="inputPassword3" placeholder="请输入密码">
			  </div>
			</div>
			<div class="form-group">
			  <div class="col-sm-offset-2 col-sm-10">
			    <button type="submit" class="btn btn-default">登录</button>
			  </div>
			</div>
			{{errmsg}}-->
</form>
</DIV>
</body>
</html>

orders/templates/htmls/result.html
{%load static%}
{% load filters %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>联金数据库查询系统</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
	<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/djangoajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/myfunction.js'%}"></script>
  </head>
  <body>
    <div >
	<div style="display: inline; bottom: 30px;" >
	<h1 style="display: inline; " >联金数据库查询系统 </h1>
	</div>
	<span><img src="{% static 'images/1528175965.png' %}" style="height: 73px;width: 255px;" id="im"></span>
	<span id='find' style="color: red"  >查询中。。。。</span>
	<form class="form-inline">
		{% csrf_token %}
		查询方式<select class="form-control" id="orderMethod">
			<option value="0">--请选择查询方式(必选)--</option>
			<option value="1">查询时间范围内订单</option>
			<option value="2">根据用户标识查询订单</option>
			<option value="3">根据订单号查询订单</option>
        </select>
		<div class="form-group">
		  <label for="exampleInputName2">开始时间</label>
		  <input type="text" class="form-control" id="startTime" style="width: 160px">
		</div>
		<div class="form-group">
		  <label for="exampleInputName2" >结束时间</label>
		  <input type="text" class="form-control" id="endTime" style="width: 160px">
		</div>
		<div class="form-group">
		  <label for="exampleInputName2">用户标识</label>
		  <input type="text" class="form-control" id="usertoken" style="width: 150px">
		</div>
		<div class="form-group">
		  <label for="exampleInputName2">订单号</label>
		  <input type="text" class="form-control" id="orderno" style="width: 150px">
		</div>
		<select class="form-control" id="orderType">
			<option value="0">--请选择订单种类--</option>
			<option value="1">全部订单</option>
			<option value="2">按摩枕订单</option>
			<option value="3">游戏订单</option>
        </select>
        <select class="form-control" id="isfilled">
        	<option value="4">--请选择分发联金状态--</option>
			<option value="3">已分发和未分发总订单</option>
			<option value="1">已分发联金订单</option>
			<option value="0">未分发联金订单</option>
        </select>
		<button type="button" class="btn btn-default" id="bt">查询</button>
    </form>
	<div id="a"></div>

			    
  </body>
</html>

orders/templates/htmls/template.html
{%load static%}
{% load filters %}
  <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/djangoajax.js' %}"></script>
<div>
	{% if flage%}
		<div style="display: inline; bottom: 30px;" >
			<h1 style="display: inline; " >联金数据库查询系统 </h1>
			</div>
		<span><img src="{% static 'images/1528175965.png' %}" style="height: 73px;width: 255px;" id="im"></span>
	{% endif %}



</div>
<div>
	<a href="/index">返回首页</a>
		<p style="color: red">当前共{{olength}}笔交易未分发成功联金</p>
		<p style="color: red">当前共{{len_pindex}}页，一页共25条记录，当前是第{{page.number}}页</p>
	

	</div>
    <table class="table table-condensed">
  		
  		<thead >
			<tr>
				<th>交易记录</th>
				<th>id</th>
				<th>用户标识</th>
				<th>订单号</th>
				<th>交易服务费</th>
				<th>交易时间</th>
				<th>是否分发</th>
				<th>交易类型</th>
			</tr>
		</thead>
		{% if olength == 0 %}
			<tbody>
			<p>当前联金都已经正常发放了</p>
			</tbody>
		{% else %}
		<tbody>	
			{% for o in page.object_list %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{o.id}}</td>
				<td>{{o.usertoken}}</td>
				<td>{{o.orderno}}</td>
				<td>{{o.orderamount}}</td>
				<td>{{ o.created_at|get_times}}</td>
				<!--<td>{{ o.created_at}}</td>-->
				{% if o.is_filled == 0 %}
					<td style="color: red">未分发</td>
				{% else %}
					<td style="color: green">已分发</td>
				{% endif %}
				<td>{{o.source_id}}</td>
			</tr>
			{% endfor %}
		</tbody>
		{% endif %}
		</table>
		<nav aria-label="Page navigation">
					<ul class="pagination">

					  {% if  page.previous_page_number > 0 %}
					  <li>
					    <a href="/result_time{{page.previous_page_number}}?" aria-label="Previous">
					      <span aria-hidden="true">上一页</span>
					    </a>
					  </li>
					  {% endif %}

					  {% for page_num in page_list %}
					          {% if page_num == page.number %}
					              <li class="active"><a href="#" ">{{ page_num }}</a></li>
					          {% else %}
					              <li><a href="/result_time{{ page_num }}">{{ page_num }}</a></li>
					          {% endif %}
					  {% endfor %}
					  {% if page.has_next %}
					  <li>
					    <a href="/result_time{{page.next_page_number}}" aria-label="Next">
					      <span aria-hidden="true">下一页</span>
					    </a>
					  </li>
					  {% endif %}
					</ul>
        </nav>
			   
			    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
			    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
			    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
			    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>